name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Fetch Repo
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Linting check
        run: npm run lint
      - name: Build
        run: npm run build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist/
